#!/usr/bin/env python3
import argparse
from pathlib import Path
import cv2
import logging
from src.config import load_config, get_config
from src.processing import Detector, run_processing
from src.hangar import HangarControlManager
from src.lib.utils import load_annotations

def parse_args():
    parser = argparse.ArgumentParser(description="Aircraft tracking pipeline")
    parser.add_argument("--video", type=str, required=True, help="Path to input video")
    parser.add_argument("--annotations", type=str, default=None, help="Path to ground truth annotations JSON")
    parser.add_argument("--output", type=str, default=None, help="Path to write output JSON (optional)")
    parser.add_argument("--no-display", action="store_true", help="Disable live visualization")
    parser.add_argument("--save-video", type=str, default=None, help="Path to save annotated output video")
    parser.add_argument("--gif", type=str, default=None, help="Path to save GIF output")
    parser.add_argument("--start", type=int, default=None, help="Start frame (0-indexed)")
    parser.add_argument("--end", type=int, default=None, help="End frame (inclusive)")
    parser.add_argument("--config", type=str, default="config.yaml", help="Path to config YAML file")
    return parser.parse_args()

def main():
    args = parse_args()
    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(name)s: %(message)s')
    logger = logging.getLogger(__name__)
    
    # Load configuration
    cfg = load_config(args.config)
    det_cfg = cfg["detection"]
    
    video_path = Path(args.video)
    assert video_path.exists(), f"Video not found: {video_path}"
    
    cap = cv2.VideoCapture(str(video_path))
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    
    logger.info(f"Video: {video_path.name} | {width}x{height} @ {fps:.1f}fps | {total_frames} frames")
    
    detector = Detector(
        model_path=det_cfg["model_path"],
        conf_thresh=det_cfg["confidence_threshold"],
        iou_thresh=det_cfg["iou_threshold"],
        verbose=det_cfg["verbose"]
    )
    hangar_manager = HangarControlManager(frame_width=width, frame_height=height, seq=str(video_path), output_path=args.output, fps=fps)
    
    gt_annotations = None
    if args.annotations:
        gt_annotations = load_annotations(args.annotations)
        logger.info(f"Loaded annotations for {len(gt_annotations)} frames")
    
    writer = None
    if args.save_video:
        fourcc = cv2.VideoWriter_fourcc(*"mp4v")
        writer = cv2.VideoWriter(args.save_video, fourcc, fps, (width, height))
    
    # Collect frames for GIF if requested
    gif_frames = [] if args.gif else None
    
    # run the processing loop (contains frame loop inside processing)
    pipeline_times = run_processing(
        cap, detector, hangar_manager, 
        writer=writer, 
        gt_annotations=gt_annotations, 
        no_display=args.no_display,
        start_frame=args.start,
        end_frame=args.end,
        gif_frames=gif_frames
    )

    cap.release()
    if writer:
        writer.release()
    cv2.destroyAllWindows()
    
    # Save GIF if requested
    if args.gif and gif_frames:
        try:
            from PIL import Image
            images = [Image.fromarray(f) for f in gif_frames]
            images[0].save(
                args.gif,
                save_all=True,
                append_images=images[1:],
                duration=int(1000 / fps),  # ms per frame
                loop=0
            )
            logger.info(f"Saved GIF to {args.gif} ({len(gif_frames)} frames)")
        except ImportError:
            logger.error("PIL not installed. Cannot save GIF. Install via: pip install Pillow")
    
    avg_ms = (sum(pipeline_times) / len(pipeline_times)) * 1000 if pipeline_times else 0
    if avg_ms > 0:
        logger.info(f"\nAvg pipeline time per frame: {avg_ms:.1f}ms ({1000/avg_ms:.1f} FPS equivalent)")
    else:
        logger.info("No frames processed.")

    # write output generated by hangar manager (only if --output was specified)
    if args.output:
        hangar_manager.write_output()

if __name__ == "__main__":
    main()